version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: "auto"
    commit-message:
      prefix: "chore(ci)"
    groups:
      actions:
        patterns:
          - "*"
